### ISSUE TITLE
在使用Tex类时遇到的问题

### ISSUE THREAD

**Issue by ghost** [manim-kindergarten/manim#13]
### Describe the error

我在使用Tex类时，遇到了一个FileNotFoundError（找不到文件）。我使用的是MiKTeX，没有指定Path变量。
### Code and Error
**Code**:

from manimlib import *
class Example(Scene):
    def construct(self):
        ireation_align = Tex(r'/sin^{n}x')
        self.add(ireation_align)
**Error**:

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310-32\Scripts\manimgl-script.py", line 33, in <module>
    sys.exit(load_entry_point('manimgl', 'console_scripts', 'manimgl')())
  File "c:\manim-master\manimlib\__main__.py", line 25, in main
    scene.run()
  File "c:\manim-master\manimlib\scene\scene.py", line 80, in run
    self.construct()
  File "C:\manim-master\vscode\Example.py", line 5, in construct
    ireation_align = Tex(r'/sin^{n}x')
  File "c:\manim-master\manimlib\mobject\svg\tex_mobject.py", line 170, in __init__
    super().__init__(full_string, **kwargs)
  File "c:\manim-master\manimlib\mobject\svg\tex_mobject.py", line 39, in __init__
    super().__init__(**kwargs)
  File "c:\manim-master\manimlib\mobject\svg\svg_mobject.py", line 62, in __init__
    self.init_svg_mobject()
  File "c:\manim-master\manimlib\mobject\svg\svg_mobject.py", line 73, in init_svg_mobject
    self.generate_mobject()
  File "c:\manim-master\manimlib\mobject\svg\svg_mobject.py", line 88, in generate_mobject
    file_path = self.get_file_path()
  File "c:\manim-master\manimlib\mobject\svg\tex_mobject.py", line 60, in get_file_path
    file_path = tex_to_svg_file(full_tex)
  File "c:\manim-master\manimlib\utils\tex_file_writing.py", line 52, in tex_to_svg_file
    tex_to_svg(tex_file_content, svg_file)
  File "c:\manim-master\manimlib\utils\tex_file_writing.py", line 60, in tex_to_svg
    svg_file = dvi_to_svg(tex_to_dvi(tex_file))
  File "c:\manim-master\manimlib\utils\tex_file_writing.py", line 91, in tex_to_dvi
    with open(log_file, "r", encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\Tex\\e1add457d41331de.log'

### Environment
**OS System**: 
**manim version**: master 
**python version**:python 3.10.8

**Comment by ghost** [comment]
我按照一篇帖子的说法，修改了defalut_config.yml，可情况没有好转。

**Comment by TonyCrane** [comment]
https://github.com/3b1b/manim/issues/1606#issuecomment-1088376571 你没装好 LaTeX

**Comment by ghost** [comment]
@TonyCrane 非常感谢
